Prep 3.0.2.6

diff --git a/update/EFA-update-script b/update/EFA-update-script
--- a/update/EFA-update-script
+++ b/update/EFA-update-script
@@ -85,6 +85,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.1" ]]
     then
@@ -108,6 +109,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.2" ]]
     then
@@ -131,6 +133,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.3" ]]
     then
@@ -154,6 +157,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.4" ]]
     then
@@ -177,6 +181,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.5" ]]
     then
@@ -200,6 +205,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.6" ]]
     then
@@ -223,6 +229,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.7" ]]
     then
@@ -245,6 +252,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.8" ]]
     then
@@ -266,6 +274,7 @@ function get_update_path() {
       update-3.0.2.3
       update-3.0.2.4
       update-3.0.2.5
+	  update-3.0.2.6
       finalize
   elif [[ $CVERSION == "EFA-3.0.0.9" ]]
       then
@@ -286,6 +295,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.0" ]]
       then
@@ -305,6 +315,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.1" ]]
       then
@@ -323,6 +334,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.2" ]]
       then
@@ -340,6 +352,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.3" ]]
       then
@@ -356,6 +369,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.4" ]]
       then
@@ -371,6 +385,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.5" ]]
       then
@@ -385,6 +400,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.6" ]]
       then
@@ -398,6 +414,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.7" ]]
       then
@@ -410,6 +427,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.8" ]]
       then
@@ -421,6 +439,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.1.9" ]]
       then
@@ -431,6 +450,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.2.0" ]]
       then
@@ -440,6 +460,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.2.1" ]]
       then
@@ -448,6 +469,7 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.2.2" ]]
       then
@@ -455,18 +477,27 @@ function get_update_path() {
         update-3.0.2.3
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
   elif [[ $CVERSION == "EFA-3.0.2.3" ]]
       then
         initialize
         update-3.0.2.4
         update-3.0.2.5
+		update-3.0.2.6
         finalize
         
   elif [[ $CVERSION == "EFA-3.0.2.4" ]]
       then
         initialize
         update-3.0.2.5
+		update-3.0.2.6
+        finalize
+		
+  elif [[ $CVERSION == "EFA-3.0.2.5" ]]
+      then
+        initialize
+        update-3.0.2.6
         finalize
   fi
 }
@@ -1029,6 +1060,36 @@ function update-3.0.2.5() {
 #----------------------------------------------------------------#
 
 #----------------------------------------------------------------#
+# Update to 3.0.2.6
+#----------------------------------------------------------------#
+function update-3.0.2.6() {
+ # Is staging area clean?
+ [[ -n $STAGING ]] && rm -rf $STAGING/*
+
+  check_disk_space
+
+  # Check for kernel update prior to package download
+  VERSION="3.0.2.6"
+  update-kernel
+
+  UPDATE="EFA-Update-3.0.2.5-3.0.2.6.tar.gz"
+  download_update
+  check_md5
+
+  # Unpack update
+  cd $STAGING
+  tar xzvf $UPDATE
+  [[ $? -ne 0 ]] && abort
+  # Bypass noexec in /tmp
+  rm -f /var/EFA/update/EFA-Version-Upgrade
+  cp $STAGING/EFA-Version-Upgrade /var/EFA/update/EFA-Version-Upgrade
+  chmod 700 /var/EFA/update/EFA-Version-Upgrade
+  /var/EFA/update/EFA-Version-Upgrade
+  [[ $? -ne 0 ]] && abort
+}
+#----------------------------------------------------------------#
+
+#----------------------------------------------------------------#
 # Function to download file
 #----------------------------------------------------------------#
 function download_update() {
@@ -1128,7 +1189,7 @@ function get_cversion() {
   if [[ $CVERSION =~ ^EFA\-[0-9]{1}\.[0-9]{1}\.[0-9]{1}\.[0-9]{1}-beta$ ]]
     then
       echo "ERROR: You seem to be running an beta version, no upgrade possible."
-      echo "ERROR: please look at http://www.efa-project.org for more information."
+      echo "ERROR: please look at https://www.efa-project.org for more information."
       echo "ERROR: exiting now"
       exit 0
   fi
